### ISSUE TITLE
The term 'docker-compose' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by ahmetarsln** [suedacicekli/ecommerceApp#1]
Docker kurulu ve docker desktopu çalışıyor fakat. docker komutunu çalıştırdığımda böyle bir hata alıyorum. Ekran fotoğrafı da koyuyorum.
![Ekran görüntüsü 2023-01-05 211815](https://user-images.githubusercontent.com/36762733/210852155-f27458d3-27e8-4ca7-9704-5d6ce4a7b850.jpg)

**Comment by suedacicekli** [comment]
docker compose up -d şeklinde deneyebilirsiniz. Yani arasında "-" olmadan. Çalışmaması halinde docker desktop'ı silip tekrar yüklemeyi deneyebilirsiniz. Bu şekilde çözüm sağlayanlar olmuş.
